version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sankar@mysql2001
      MYSQL_DATABASE: Speech_transcriptions
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pSankar@mysql2001"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s   # give mysql some time to initialize

  backend:
    build: ./backend
    container_name: speech2text-backend-container
    ports:
      - "8070:8070"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://root:Sankar%40mysql2001@mysql:3306/Speech_transcriptions"

  frontend:
    build: ./frontend
    container_name: speech2text-frontend-container
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      FASTAPI_URL: "http://backend:8070"

volumes:
  mysql_data:
